import React, { useState, memo } from 'react';
import { useLocalization } from '../hooks/useLocalization';
import { getClinicalDoctorReport } from '../services/geminiService';
import { MoodEntry, JournalEntry, DoctorReport } from '../types';
import SimpleMarkdownRenderer from './SimpleMarkdownRenderer';

interface ClinicalSyncCardProps {
    moods: MoodEntry[];
    journals: JournalEntry[];
    programName: string;
}

const ClinicalSyncCard: React.FC<ClinicalSyncCardProps> = ({ moods, journals, programName }) => {
    const { t, language } = useLocalization();
    const [report, setReport] = useState<DoctorReport | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [isOpen, setIsOpen] = useState(false);

    const generateReport = async () => {
        setIsLoading(true);
        try {
            const data = await getClinicalDoctorReport(moods, journals, programName, language);
            setReport(data);
            setIsOpen(true);
        } catch (error) {
            console.error(error);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <section className="bg-white/80 dark:bg-base-900/80 backdrop-blur-2xl p-8 rounded-[2.5rem] shadow-soft border border-white/40 dark:border-white/10 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4">
                <div className="bg-primary-500/10 text-primary-600 dark:text-primary-400 px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-widest">
                    HIPAA Friendly Mode
                </div>
            </div>
            
            <div className="flex items-center gap-6 mb-6">
                <div className="w-16 h-16 bg-primary-500 text-white rounded-2xl flex items-center justify-center shadow-lg shadow-primary-500/20">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                </div>
                <div>
                    <h2 className="text-xl font-black text-base-900 dark:text-white uppercase tracking-tight">Clinical Sync</h2>
                    <p className="text-sm text-base-500 dark:text-base-400">Generate a professional progress summary for your doctor or therapist.</p>
                </div>
            </div>

            {!report ? (
                <button 
                    onClick={generateReport}
                    disabled={isLoading}
                    className="w-full bg-base-900 text-white dark:bg-base-100 dark:text-base-900 font-black py-4 rounded-2xl hover:scale-[1.02] transition-all flex items-center justify-center gap-3 disabled:opacity-50"
                >
                    {isLoading ? (
                        <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    ) : 'Prepare Medical Summary'}
                </button>
            ) : (
                <button 
                    onClick={() => setIsOpen(true)}
                    className="w-full border-2 border-primary-500 text-primary-600 dark:text-primary-400 font-black py-4 rounded-2xl hover:bg-primary-500 hover:text-white transition-all"
                >
                    View Prepared Summary
                </button>
            )}

            {isOpen && report && (
                <div className="fixed inset-0 z-[200] bg-base-900/90 backdrop-blur-md flex items-center justify-center p-4">
                    <div className="bg-white dark:bg-base-800 w-full max-w-2xl max-h-[90vh] rounded-[3rem] overflow-hidden flex flex-col shadow-2xl animate-enter">
                        <div className="p-8 border-b border-base-100 dark:border-base-700 flex justify-between items-center">
                            <div>
                                <h3 className="text-2xl font-black text-base-900 dark:text-white">Patient Progress Report</h3>
                                <p className="text-xs font-bold text-primary-500 uppercase tracking-widest mt-1">Generated by Aman AI Companion</p>
                            </div>
                            <button onClick={() => setIsOpen(false)} className="p-2 bg-base-100 dark:bg-base-700 rounded-full">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M6 18L18 6M6 6l12 12" /></svg>
                            </button>
                        </div>
                        <div className="p-8 overflow-y-auto space-y-8">
                            <section>
                                <h4 className="text-[10px] font-black uppercase text-base-400 tracking-[0.2em] mb-3">Clinical Situation</h4>
                                <p className="text-base text-base-800 dark:text-base-200 leading-relaxed">{report.summary}</p>
                            </section>
                            
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <section>
                                    <h4 className="text-[10px] font-black uppercase text-base-400 tracking-[0.2em] mb-3">Identified Triggers</h4>
                                    <ul className="space-y-2">
                                        {report.topTriggers.map((t, i) => (
                                            <li key={i} className="flex items-center gap-2 text-sm text-base-700 dark:text-base-300">
                                                <span className="w-1.5 h-1.5 rounded-full bg-warning-500" /> {t}
                                            </li>
                                        ))}
                                    </ul>
                                </section>
                                <section>
                                    <h4 className="text-[10px] font-black uppercase text-base-400 tracking-[0.2em] mb-3">Positive Observations</h4>
                                    <ul className="space-y-2">
                                        {report.positives.map((p, i) => (
                                            <li key={i} className="flex items-center gap-2 text-sm text-base-700 dark:text-base-300">
                                                <span className="w-1.5 h-1.5 rounded-full bg-accent-500" /> {p}
                                            </li>
                                        ))}
                                    </ul>
                                </section>
                            </div>

                            <section className="p-6 bg-base-50 dark:bg-base-900 rounded-3xl border border-base-200 dark:border-base-700">
                                <h4 className="text-[10px] font-black uppercase text-base-400 tracking-[0.2em] mb-3">Professional Concerns</h4>
                                <ul className="space-y-2">
                                    {report.concerns.map((c, i) => (
                                        <li key={i} className="text-sm font-bold text-base-800 dark:text-base-200">• {c}</li>
                                    ))}
                                </ul>
                            </section>
                        </div>
                        <div className="p-8 bg-base-100 dark:bg-base-900/50 text-center">
                            <p className="text-[9px] font-bold text-base-500 uppercase tracking-widest">Confidential Report for Professional Use Only</p>
                        </div>
                    </div>
                </div>
            )}
        </section>
    );
};

export default memo(ClinicalSyncCard);